- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=feature, --markdown-linebreak-ext=yaml, --markdown-linebreak-ext=yml, --markdown-linebreak-ext=jps]
  - id: check-json
    exclude: .vscode/*
  - id: pretty-format-json
    exclude: .vscode/*
    args: [--autofix, --indent=2]

