package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.XmlReport
import jetbrains.buildServer.configs.kotlin.buildFeatures.xmlReport
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Integration'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Integration")) {
    params {
        add {
            param("teamcity.ui.settings.readOnly", "false")
        }
    }

    features {
        add {
            xmlReport {
                id = "BUILD_EXT_3"
                reportType = XmlReport.XmlReportType.JUNIT
                rules = "+:mutmut.xml"
            }
        }
    }
}
